In [7]:
#task-1
import numpy as np

ratings = np.array([
    [4, 5, 3, 4, 5],
    [5, 4, 4, 3, 5],
    [3, 5, 4, 5, 4],
    [4, 3, 5, 4, 3]
])

print("ratings:")
print(ratings)

second_third_users=ratings[1:3]
print("second third user ratings:")
print(second_third_users)

ratings:
[[4 5 3 4 5]
 [5 4 4 3 5]
 [3 5 4 5 4]
 [4 3 5 4 3]]
second third user ratings:
[[5 4 4 3 5]
 [3 5 4 5 4]]


In [10]:
#task-2
steps = np.array([7500, 8200, 9000, 6500, 8500, 7200, 10000, 7800, 8800, 6000])

# Select days where steps are greater than 8000
result = steps[steps > 8000]

print("Steps greater than 8000:", result)

Steps greater than 8000: [ 8200  9000  8500 10000  8800]


In [17]:
#task-3
scores = np.array([185, 210, 176, 195, 220, 168, 205, 190])
selected_scores=scores[[1,4,6]]

print("scores:",scores)
print("selected scores:",selected_scores)

scores: [185 210 176 195 220 168 205 190]
selected scores: [210 220 205]


In [21]:
#task-4
prices = np.array([1000, 2500, 5000, 7500, 10000])
discount_prices=prices*0.90

print("original prices:",prices)
print("discount price:",discount_prices)

original prices: [ 1000  2500  5000  7500 10000]
discount price: [ 900. 2250. 4500. 6750. 9000.]


In [22]:
#task-5
ratings = np.array([5, -2, 4, -1, 0, 3, -4, 5])
ratings[ratings < 0] = 0

print("Updated Ratings:", ratings)

Updated Ratings: [5 0 4 0 0 3 0 5]
