In [3]:
#task-1
import numpy as np

In [6]:
#task-2
followers=np.array([1200, 15000, 67000, 340000, 1250000])
print("followers:",followers)
print("shape:",followers.shape)
print("Number of dimensions:", followers.ndim)
print("Data type:", followers.dtype)

followers: [   1200   15000   67000  340000 1250000]
shape: (5,)
Number of dimensions: 1
Data type: int64


In [10]:
#task-3
order_id=np.arange(101,111)
print("order ids:",order_id)
print("size:",order_id.size)

order ids: [101 102 103 104 105 106 107 108 109 110]
size: 10


In [13]:
#task-4
matrix=np.eye(3)
print("like identity matrix:")
print(matrix)

like identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
#task-5
scores= [45, 67, 120, 89, 54] 
score_array=np.array(scores)
print("score array:",score_array)
print("bytes per score:",score_array.itemsize)

score array: [ 45  67 120  89  54]
bytes per score: 8
