In [1]:
import numpy as np

In [2]:
#task1
friend1 = np.array([7000, 8500, 9000, 7500, 10000, 11000, 9500])
friend2 = np.array([6500, 8000, 9200, 7000, 9800, 10500, 9000])

print("Friend 1 Steps:", friend1)
print("Friend 2 Steps:", friend2)

print("\nAddition:")
print(friend1 + friend2)

print("\nSubtraction:")
print(friend1 - friend2)

print("\nMultiplication:")
print(friend1 * friend2)

print("\nDivision:")
print(friend1 / friend2)

Friend 1 Steps: [ 7000  8500  9000  7500 10000 11000  9500]
Friend 2 Steps: [ 6500  8000  9200  7000  9800 10500  9000]

Addition:
[13500 16500 18200 14500 19800 21500 18500]

Subtraction:
[ 500  500 -200  500  200  500  500]

Multiplication:
[ 45500000  68000000  82800000  52500000  98000000 115500000  85500000]

Division:
[1.07692308 1.0625     0.97826087 1.07142857 1.02040816 1.04761905
 1.05555556]


In [3]:
#task2
user_preferences = np.array([
    [5, 3, 4],
    [4, 5, 2],
    [3, 4, 5]
])

song_popularity = np.array([
    [2, 1, 3],
    [4, 2, 1],
    [3, 5, 2]
])

recommendation_dot = np.dot(user_preferences, song_popularity)
recommendation_matmul = np.matmul(user_preferences, song_popularity)

print("\nRecommendation Matrix using dot():")
print(recommendation_dot)

print("\nRecommendation Matrix using matmul():")
print(recommendation_matmul)



Recommendation Matrix using dot():
[[34 31 26]
 [34 24 21]
 [37 36 23]]

Recommendation Matrix using matmul():
[[34 31 26]
 [34 24 21]
 [37 36 23]]


In [4]:
#task3
image = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120],
    [130, 140, 150, 160]
])

rotated_image = image.T

print("\nTransposed Image:")
print(rotated_image)

print("Mean:", np.mean(image))
print("Median:", np.median(image))
print("Standard Deviation:", np.std(image))
print("Variance:", np.var(image))


Transposed Image:
[[ 10  50  90 130]
 [ 20  60 100 140]
 [ 30  70 110 150]
 [ 40  80 120 160]]
Mean: 85.0
Median: 85.0
Standard Deviation: 46.09772228646444
Variance: 2125.0


In [5]:
#task4
matrix = np.array([
    [4, 2, 1],
    [2, 5, 3],
    [1, 3, 6]
])

print("\nDeterminant:")
print(np.linalg.det(matrix))

print("\nInverse:")
print(np.linalg.inv(matrix))

eigenvalues, eigenvectors = np.linalg.eig(matrix)

print("\nEigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)


Determinant:
66.99999999999997

Inverse:
[[ 0.31343284 -0.13432836  0.01492537]
 [-0.13432836  0.34328358 -0.14925373]
 [ 0.01492537 -0.14925373  0.23880597]]

Eigenvalues:
[9.34849393+0.j 3.73015912+0.j 1.92134694+0.j]

Eigenvectors:
[[-0.3650547 +0.j -0.77587586+0.j  0.5145403 +0.j]
 [-0.63657455+0.j -0.19527095+0.j -0.74608451+0.j]
 [-0.67934373+0.j  0.59990492+0.j  0.42261825+0.j]]


In [6]:
#task5
orders = np.array([
    [120, 135, 150, 140, 160, 170],
    [110, 125, 145, 155, 165, 175]
])

print("\nOriginal Shape:", orders.shape)

reshaped = orders.reshape(3, 4)
print("\nReshaped (3x4):")
print(reshaped)

flattened = orders.flatten()
print("\nFlattened:")
print(flattened)

part1, part2 = np.split(flattened, 2)

print("\nPart 1:")
print(part1)

print("\nPart 2:")
print(part2)

stacked = np.vstack((part1, part2))

print("\nVertically Stacked:")
print(stacked)


Original Shape: (2, 6)

Reshaped (3x4):
[[120 135 150 140]
 [160 170 110 125]
 [145 155 165 175]]

Flattened:
[120 135 150 140 160 170 110 125 145 155 165 175]

Part 1:
[120 135 150 140 160 170]

Part 2:
[110 125 145 155 165 175]

Vertically Stacked:
[[120 135 150 140 160 170]
 [110 125 145 155 165 175]]
